---
title: 'Colon Adenocarcinoma (COAD) Exploratory Data Analysis'
author: "Sehyun Oh, Britney Pheng"
date: "`r format(Sys.time(), '%B %d, %Y')`"
format:
    html:
        fontsize: 14pxs
        toc: true
        top-depth: 3
output: html_document
---
# Initial Setup
## Load packages
```{r packages, warning=FALSE, message=FALSE}
suppressPackageStartupMessages({
  # BiocManager
  library(GenomicSuperSignature)
  library(curatedTCGAData)
  library(MultiAssayExperiment)
  library(TCGAutils)
  library(ComplexHeatmap)
  
  # CRAN
  library(tidyverse) # includes dplyr, ggplot2, magrittr, tidyr
  library(magick)
  library(wordcloud)
  library(ztable)
  library(metafolio)
})
```

## Create TCGA dataset
```{r}
# data_dir <- "~/Documents/GitHub/GSS-Britney/data"
# 
# ## Raw read counts from GSE62944 from ExperimentHub
# tcga <- GSEABenchmarkeR::loadEData("tcga", cache = FALSE, paired = FALSE, map2entrez = FALSE)
# 
# ## log2 transformation
# assay(tcga$COAD) <- log2(assay(tcga$COAD) + 1)
# assay(tcga$HNSC) <- log2(assay(tcga$HNSC) + 1)
# 
# TCGA_validationDatasets <- vector(mode = "list", length = 2)
# names(TCGA_validationDatasets) <- c("COAD", "HNSC")
# TCGA_validationDatasets[[1]] <- tcga$COAD
# TCGA_validationDatasets[[2]] <- tcga$HNSC
# 
# ## TCGA-OVC dataset from curatedOvarianData
# BiocManager::install('curatedOvarianData')
# library(curatedOvarianData)
# data(TCGA.RNASeqV2_eset)
# x <- as(TCGA.RNASeqV2_eset, "SummarizedExperiment")
# 
# rs <- rowSums(assay(x) > 2)
# keep <-  rs >= ncol(x) / 2
# tcga_ovc <- x[keep,]
# TCGA_validationDatasets[["OV"]] <- tcga_ovc
# 
# save(TCGA_validationDatasets, file = file.path(data_dir, "TCGA_validationDatasets.rda"))
```

## Load TCGA dataset
```{r}
load('~/Documents/GitHub/GSS-Britney/data/TCGA_validationDatasets.rda')
datasets <- TCGA_validationDatasets[1:3]
```

## Load RAVmodel
```{r message=FALSE, warning=FALSE}
RAVmodel <- getModel('C2', load=TRUE)
```

## Select COAD RNA metadata
```{r message=FALSE, warning=FALSE}
coad <- curatedTCGAData(diseaseCode = 'COAD',
                        assays = 'RNA*',
                        version = '2.0.1',
                        dry.run = FALSE)

coad_rna <- getWithColData(coad,
                           'COAD_RNASeq2Gene-20160128',
                           mode = 'append')

coad_meta <- colData(coad_rna)
```

# heatmapTable: COAD
```{r message=FALSE}
validate_coad <- validate(datasets[['COAD']], RAVmodel)
heatmapTable(validate_coad, RAVmodel)
```
```{r message=FALSE}
assay(coad_rna) <- log2(assay(coad_rna) + 1)

validate_coad_rna <- validate(coad_rna, RAVmodel)
heatmapTable(validate_coad_rna, RAVmodel)
```
# Subset
## Filter attributes
```{r}
sparsity_summary <- table(colSums(is.na(coad_meta)))
sparsity_summary
```
## Sparsity Plot
```{r echo=FALSE}
plot(stack(sparsity_summary)$ind,
     stack(sparsity_summary)$values)
```
```{r}
# Select columns with >10% completeness
keep_attribute_ind <- which(colSums(!is.na(coad_meta)) > round(nrow(coad_meta)/10))
meta_sub <- coad_meta[keep_attribute_ind]
meta_sub <- subset(meta_sub, select= -patientID)
```

```{r}
# Check for data types in listData
unique(sapply(coad_meta@listData, type))

charcTb <- meta_sub[, sapply(meta_sub, class) == 'character']
numTb <- meta_sub[, sapply(meta_sub, class) %in% c('numeric', 'integer')]
```

```{r}
# Calculate validation scores
sampleScore <- calculateScore(coad_rna, RAVmodel)
```

```{r}
validated_ind <- validatedSignatures(validate_coad_rna, num.out = 30, RAVmodel, swCutoff = 0.5, indexOnly = TRUE)

# Subset sampleScore to join with MCPcounter
sampleScore_sub <- sampleScore[, validated_ind] %>% as.data.frame()
```
# Calculate R-Squared Value for Numeric Variables
```{r calculateRsq}
# R squared value function
calculateRsq <- function (x, y) stats::cor(x, y, use = 'na.or.complete') ^ 2
```

```{r warning=FALSE}
# Calculate r-squared for numeric attributes
rsq_numAttr <- as.data.frame(matrix(nrow = ncol(numTb),
                                    ncol = ncol(sampleScore_sub)))

colnames(rsq_numAttr) <- colnames(sampleScore_sub)
rownames(rsq_numAttr) <- colnames(numTb)

for (i in seq_len(ncol(numTb))) {
  for (j in seq_len(ncol(sampleScore_sub))) {
    rsq <- calculateRsq(numTb[, i], sampleScore_sub[, j])
    rsq_numAttr[i, j] <- rsq
  }
}

rsq_numAttr <- na.omit(rsq_numAttr)
```

```{r}
max_rav <- apply(rsq_numAttr, 1, max)
max_attr <- which(max_rav > 0.5)

target_rsq <- rsq_numAttr[max_attr,]
```


# heatmapTable
```{r results='asis'}
options(ztable.type='html')
z = ztable(target_rsq)
z %>% makeHeatmap(palette='Purples')
```

```{r}
# Remove batch effect variables
batch_num_ind <- grep('analyte|portion|procurement|aliquot|uuid|barcode',
                  rownames(rsq_numAttr))
rsq_numAttr_no_batch <- rsq_numAttr[-batch_num_ind,]
```

```{r}
max_rav <- apply(rsq_numAttr_no_batch, 1, max)
max_rav[max_attr]
```

```{r}
heatmap(as.matrix(rsq_numAttr_no_batch))
```
# Calculate F-statistic (ANOVA) for Character Variables
```{r}
# Convert to factor data type
factorTb <- meta_sub[, sapply(meta_sub, class) == 'character']

factorTb[sapply(factorTb, is.character)] <- lapply(factorTb[sapply(factorTb, is.character)], factor, exclude = NULL)

factor_ind <- c()

# Select for factors with at least two possible values
for (i in 1:length(factorTb)) {
  if (nlevels(factorTb[,i]) > 1) {
    factor_ind <- c(factor_ind, i)
  }
}

new_factorTb <- factorTb[,factor_ind]
```

```{r}
aov_res <- as.data.frame(matrix(nrow = ncol(new_factorTb),
                                ncol = ncol(sampleScore_sub)))

rownames(aov_res) <- colnames(new_factorTb)
colnames(aov_res) <- colnames(sampleScore_sub)

aov_coad_fvalue <- aov_res
aov_coad_pvalue <- aov_res

for (i in seq_len(ncol(sampleScore_sub))) {
  for (j in seq_len(ncol(new_factorTb))) {
    
    ## ANOVA
    aov <- aov(sampleScore_sub[, i] ~ new_factorTb[, j])
    
    ## F-statistic
    fval <- summary(aov)[[1]]$`F value`[1]
    aov_coad_fvalue[j, i] <- fval
    
    ## p-value
    pval <- summary(aov)[[1]]$`Pr(>F)`[1]
    aov_coad_pvalue[j, i] <- pval
  }
}
```

```{r}
# Select for p-values < 0.01
min_rav <- apply(aov_coad_pvalue, 1, min)
min_attr <- which(min_rav < 0.01)

target_coad_aov_fvalue <- aov_coad_fvalue[min_attr,]
target_coad_aov_pvalue <- aov_coad_pvalue[min_attr,]
```

```{r}
batch_char_ind <- grep('analyte|portion|procurement|aliquot|uuid|barcode',
                       rownames(target_coad_aov_fvalue))
coad_aov_fvalue <- target_coad_aov_fvalue[-batch_char_ind,]
coad_aov_pvalue <- target_coad_aov_pvalue[-batch_char_ind,]
```

```{r}
heatmap(as.matrix(coad_aov_fvalue), main = 'COAD F-Statistics')
```

```{r}
sig_fval <- as.data.frame(matrix(nrow = ncol(new_factorTb),
                                ncol = ncol(sampleScore_sub)))

rownames(sig_fval) <- colnames(new_factorTb)
colnames(sig_fval) <- colnames(sampleScore_sub)

for (i in seq_len(ncol(sampleScore_sub))) {
  for (j in seq_len(ncol(new_factorTb))) {
    
    if (!is.null(summary(aov(sampleScore_sub[, i] ~ new_factorTb[, j]))[[1]]$`Pr(>F)`[1])) {
      
      if (!is.null(summary(aov(sampleScore_sub[, i] ~ new_factorTb[, j]))[[1]]$`F value`[1]) &
          (summary(aov(sampleScore_sub[, i] ~ new_factorTb[, j]))[[1]]$`Pr(>F)`[1] < 0.01)) {
        sig_fval[j, i] <- summary(aov(sampleScore_sub[, i] ~ new_factorTb[, j]))[[1]]$`F value`[1]
      } else {
        next
      }
    } else {
      next
    }
  }
}

fstat_ind <- c()

for (i in seq_len(nrow(sig_fval))) {
  if (sum(is.na(sig_fval[i, ])) < 11) {
    fstat_ind <- c(fstat_ind, i)
  } else {
    next
  }
}

sig_fval <- sig_fval[fstat_ind,]

batch_char_ind_2 <- grep('analyte|portion|procurement|aliquot|uuid|barcode',
                  rownames(sig_fval))
sig_fval <- sig_fval[-batch_char_ind_2,]

```

```{r results='asis', message=FALSE}
options(ztable.type='html')
ztable(sig_fval) %>%
  makeHeatmap(palette = 'Blues') %>%
  print(caption='ANOVA F-stats with p-values < 0.01')
```
## RAV Exploration
```{r}
ind <- 1002
findStudiesInCluster(RAVmodel, ind, studyTitle = TRUE)
drawWordcloud(RAVmodel, ind)
```

