---
title: "Untitled"
format: html
editor: visual
---

```{r}
library(ztable)
library(dplyr)
```

```{r}
aov_fvalue <- read.csv("aov_fvalue.csv", row.names = 1)
aov_pvalue <- read.csv("aov_pvalue.csv", row.names = 1)
```

```{r}
## Remove potential batch effects-associated attributes
batch_terms <- "analyte|portion|procurement|aliquot|uuid|barcode|biospecimen"
batch_ind <- grep(batch_terms, 
                  rownames(aov_fvalue))
```

```{r echo=FALSE, eval=FALSE}
apply(aov_fvalue[-batch_ind,], 1, max) %>% hist
```

```{r}
aov_pvalue_no_batch <- aov_pvalue[-batch_ind,]

aov_fvalue_no_batch <- aov_fvalue[-batch_ind,]
r_ind <- which(apply(aov_fvalue_no_batch, 1, max) > 5)
c_ind <- which(apply(aov_fvalue_no_batch, 2, max) > 5)
aov_fvalue_sub <- aov_fvalue_no_batch[r_ind, c_ind] %>% as.data.frame
```

```{r fig.width=10, fig.height=10}
heatmap(as.matrix(aov_fvalue_sub))
```

```{r results='asis'}
options(ztable.type = "html")
ztable(aov_fvalue_sub) %>%
  makeHeatmap() %>%
  print(caption = "ANOVA F-values")
```

```{r results='asis'}
beep <- merge(aov_fvalue_no_batch, aov_pvalue_no_batch, by='row.names')
boop <- select(beep, contains(".y"))

beep_x_index <- grep(".x", colnames(beep)) %>% c()
beep_y_index <- grep(".y", colnames(beep)) %>% c()

options(ztable.type = "html")
ztable(beep) %>%
  makeHeatmap(rows=beep[beep[,beep_y_index]<=0.05]) %>%
  print(caption="ANOVA F-values & p-values")
  
  
```
